spring:
  application:
    name: conduit-skwzz

  datasource:
    url: jdbc:mariadb://localhost:3307/conduit
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

jwt:
  secret-key: d+tiN9EN4+gm/6AoTDqZwglMYkC2a5YbtjOsvD7VCqM=
  validity-in-milliseconds: 60000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG