spring:
  application:
    name: conduit-skwzz

  datasource:
    url: jdbc:mariadb://localhost:3307/conduit
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
