DROP TABLE IF EXISTS `member`;

CREATE TABLE `member` (
    idx BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    bio VARCHAR(255),
    image VARCHAR(255)
);